# Generated by Django 5.2.17 on 2026-09-26 16:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Catalogue id, e.g. grewingk_2021.", unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("lidar", "Lidar survey"),
                            ("context", "Regional context DEM"),
                        ],
                        default="lidar",
                        max_length=10,
                    ),
                ),
                (
                    "encoding",
                    models.CharField(
                        choices=[
                            ("mapbox", "Mapbox terrain-RGB (PMTiles or tiles)"),
                            ("terrarium", "Terrarium tiles"),
                            ("imageserver", "ArcGIS ImageServer (float32 export)"),
                        ],
                        default="mapbox",
                        max_length=12,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "gated",
                    models.BooleanField(
                        default=False,
                        help_text="Only data_users see it. Gated lidar also needs trailgeek's own ranged proxy (not built yet).",
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("product", models.CharField(blank=True, max_length=100)),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="Who flew / published it.", max_length=300
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=500)),
                (
                    "horizontal_crs",
                    models.CharField(
                        blank=True, help_text="e.g. EPSG:6334", max_length=40
                    ),
                ),
                ("vertical_datum", models.CharField(blank=True, max_length=40)),
                ("native_res_m", models.FloatField(blank=True, null=True)),
                ("min_zoom", models.IntegerField(default=0)),
                ("max_zoom", models.IntegerField(default=15)),
                (
                    "footprint",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "bounds",
                    models.JSONField(blank=True, help_text="[w, s, e, n]", null=True),
                ),
                ("coverage_km2", models.FloatField(blank=True, null=True)),
                ("z_min", models.FloatField(blank=True, null=True)),
                ("z_max", models.FloatField(blank=True, null=True)),
                (
                    "cog_url",
                    models.URLField(
                        blank=True,
                        help_text="Archive COG (the worker samples this).",
                        max_length=500,
                    ),
                ),
                ("pmtiles_url", models.URLField(blank=True, max_length=500)),
                (
                    "tiles_url",
                    models.CharField(
                        blank=True,
                        help_text="Per-tile URL template ({z}/{x}/{y}).",
                        max_length=500,
                    ),
                ),
                ("slope_url", models.URLField(blank=True, max_length=500)),
                ("slope_tiles_url", models.CharField(blank=True, max_length=500)),
                ("slope_step", models.FloatField(blank=True, null=True)),
                ("fill_mode", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "DEM source",
                "ordering": ["kind", "region", "title"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("gated", "Signed-in collaborators"),
                            ("private", "Owner and project members"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, help_text="Markdown.")),
                (
                    "aoi",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, help_text="Area of interest.", null=True, srid=4326
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Evaluator settings; empty means defaults.",
                    ),
                ),
                (
                    "dem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="core.demsource",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="trail_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Alignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "priority",
                    models.IntegerField(default=1, help_text="1 = primary candidate."),
                ),
                ("trailhead", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                (
                    "runs_uphill",
                    models.BooleanField(
                        blank=True,
                        editable=False,
                        help_text="Set by the evaluator.",
                        null=True,
                    ),
                ),
                ("length_m", models.FloatField(default=0, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alignments",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="Trail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("gated", "Signed-in collaborators"),
                            ("private", "Owner and project members"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, help_text="Markdown.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("existing", "Existing"),
                            ("proposed", "Proposed"),
                            ("historic", "Historic"),
                        ],
                        default="existing",
                        max_length=10,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Where the line came from.",
                        max_length=300,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
                ),
                ("length_m", models.FloatField(default=0, editable=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("gated", "Signed-in collaborators"),
                            ("private", "Owner and project members"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "device",
                    models.CharField(
                        blank=True, help_text="GPX creator string.", max_length=100
                    ),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(
                        dim=3, srid=4326
                    ),
                ),
                ("has_elevation", models.BooleanField(default=False)),
                ("times", models.JSONField(blank=True, editable=False, null=True)),
                ("original", models.FileField(blank=True, upload_to="tracks/%Y/")),
                ("point_count", models.IntegerField(default=0, editable=False)),
                ("length_m", models.FloatField(default=0, editable=False)),
                ("climb_m", models.FloatField(default=0, editable=False)),
                ("descent_m", models.FloatField(default=0, editable=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracks",
                        to="core.trail",
                    ),
                ),
            ],
            options={
                "ordering": ["-taken_at", "-created"],
            },
        ),
    ]
