# Generated by Django 5.2.17 on 2026-09-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demsource',
            name='vertical_datum',
            field=models.CharField(blank=True, help_text="Free text from the catalogue, e.g. 'NAVD88 (GEOID12B, after vertical_shift_m)'.", max_length=200),
        ),
    ]
