# Generated by Django 5.2.17 on 2026-09-27 23:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


def one_leg_per_alignment(apps, schema_editor):
    """Existing alignments were single lines: give each one leg of new
    construction covering its whole geometry, so every alignment is
    leg-backed from here on."""
    Alignment = apps.get_model("core", "Alignment")
    Leg = apps.get_model("core", "Leg")
    for a in Alignment.objects.exclude(geom=None):
        Leg.objects.create(alignment=a, order=0, kind="new", geom=a.geom, length_m=a.length_m)


def drop_legs(apps, schema_editor):
    apps.get_model("core", "Leg").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_demsource_vertical_datum_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="alignment",
            name="evaluated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="alignment",
            name="evaluation",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="alignment",
            name="evaluation_error",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="alignment",
            name="evaluation_status",
            field=models.CharField(
                choices=[
                    ("none", "Not evaluated"),
                    ("queued", "Queued"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="none",
                editable=False,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="alignment",
            name="headline",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text="The few numbers compare tables show, kept apart from the (large) evaluation.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alignment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The alignment this one was duplicated from, when it is a variant.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="core.alignment",
            ),
        ),
        migrations.AddField(
            model_name="alignment",
            name="source",
            field=models.CharField(
                blank=True, help_text="Import provenance, if imported.", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="trail",
            name="builder",
            field=models.CharField(
                blank=True, help_text="Who built or maintains it.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="trail",
            name="source_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Import provenance, e.g. '200111_TRAILS#17'. Re-importing a file replaces its rows.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="trail",
            name="trail_class",
            field=models.CharField(
                choices=[
                    ("major", "Major trail"),
                    ("regular", "Trail"),
                    ("route", "Route (unmaintained / cross-country)"),
                    ("ski", "Ski trail"),
                    ("sidewalk", "Sidewalk / path"),
                    ("abandoned", "Abandoned"),
                    ("other", "Other"),
                ],
                default="regular",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="alignment",
            name="geom",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True, editable=False, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="trail",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name="Leg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("existing", "Existing trail"),
                            ("new", "New construction"),
                            ("reroute", "Reroute"),
                            ("restore", "Restoration"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "effort_factor",
                    models.FloatField(
                        default=1.0,
                        help_text="Multiplier on the rubric's construction days, e.g. 0.5 for a restoration where half the tread survives. Ignored for existing trail.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                ("length_m", models.FloatField(default=0, editable=False)),
                (
                    "stats",
                    models.JSONField(
                        blank=True,
                        editable=False,
                        help_text="From the last evaluation.",
                        null=True,
                    ),
                ),
                (
                    "alignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="core.alignment",
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        blank=True,
                        help_text="For existing-trail legs: the trail followed (the main one, if several).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legs",
                        to="core.trail",
                    ),
                ),
            ],
            options={
                "ordering": ["alignment", "order"],
            },
        ),
        migrations.RunPython(one_leg_per_alignment, drop_legs),
    ]
